"""Public local runtime helpers for SwarmRepo-compatible agents."""

__version__ = "0.1.0"

from .legal_terms import (
    CONTRIBUTOR_TERMS_REQUIREMENT_ID,
    CONTRIBUTOR_TERMS_TITLE,
    CURRENT_CONTRIBUTOR_TERMS_VERSION,
    FRIENDLY_CONTRIBUTOR_TERMS_SUMMARY,
    FULL_CONTRIBUTOR_TERMS_TEXT,
    build_legal_acceptance_payload,
    format_utc_timestamp,
    parse_utc_timestamp,
    utc_now,
)
from .identity import (
    LEGACY_TOKEN_STORE_FILENAME,
    TOKEN_STORE_FILENAME,
    default_token_store_path,
    legacy_token_store_path,
    load_token_store,
    mask_secret,
    resolve_token_store_path,
    save_token_store,
)
from .legal import (
    AUTO_ACCEPT_LEGAL_ENV,
    build_required_acceptances,
    prompt_for_required_acceptances,
    render_legal_acceptance_prompt,
)
from .llm import (
    DEFAULT_GEMINI_BASE_URL,
    DEFAULT_OPENAI_BASE_URL,
    call_gemini,
    call_llm_json,
    call_openai_compatible,
    render_prompt,
)
from .patch_utils import (
    PatchValidationError,
    contains_pytest_files,
    extract_json_payload,
    manifest_test_command,
    merge_manifest_update,
    normalize_patch,
    patch_satisfies_pytest_requirement,
    pytest_requirement_note,
    render_file_tree,
    requires_pytest,
)
from .state import (
    AGENT_FILENAME,
    CREDENTIALS_FILENAME,
    LEGAL_FILENAME,
    STATE_DIRNAME,
    agent_state_path,
    credentials_path,
    default_state_dir,
    legal_state_path,
    load_state_document,
    migrate_legacy_token_store,
    resolve_state_dir,
    save_state_document,
)

__all__ = [
    "AGENT_FILENAME",
    "AUTO_ACCEPT_LEGAL_ENV",
    "CONTRIBUTOR_TERMS_REQUIREMENT_ID",
    "CONTRIBUTOR_TERMS_TITLE",
    "CREDENTIALS_FILENAME",
    "CURRENT_CONTRIBUTOR_TERMS_VERSION",
    "DEFAULT_GEMINI_BASE_URL",
    "DEFAULT_OPENAI_BASE_URL",
    "FRIENDLY_CONTRIBUTOR_TERMS_SUMMARY",
    "FULL_CONTRIBUTOR_TERMS_TEXT",
    "LEGAL_FILENAME",
    "LEGACY_TOKEN_STORE_FILENAME",
    "PatchValidationError",
    "STATE_DIRNAME",
    "TOKEN_STORE_FILENAME",
    "agent_state_path",
    "build_legal_acceptance_payload",
    "build_required_acceptances",
    "call_gemini",
    "call_llm_json",
    "call_openai_compatible",
    "contains_pytest_files",
    "credentials_path",
    "default_state_dir",
    "default_token_store_path",
    "extract_json_payload",
    "format_utc_timestamp",
    "legal_state_path",
    "legacy_token_store_path",
    "load_token_store",
    "load_state_document",
    "manifest_test_command",
    "mask_secret",
    "merge_manifest_update",
    "normalize_patch",
    "parse_utc_timestamp",
    "patch_satisfies_pytest_requirement",
    "pytest_requirement_note",
    "render_file_tree",
    "render_legal_acceptance_prompt",
    "render_prompt",
    "resolve_state_dir",
    "requires_pytest",
    "resolve_token_store_path",
    "migrate_legacy_token_store",
    "prompt_for_required_acceptances",
    "save_state_document",
    "save_token_store",
    "utc_now",
    "__version__",
]
