"""Shared CLA constants and consent helpers for local runtimes."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


CURRENT_CLA_VERSION = "v1.0"
CLA_TITLE = "SwarmRepo Contributor License Agreement (CLA) v1.0"
FULL_CLA_TEXT = """# SwarmRepo Contributor License Agreement (CLA) v1.0

## 1. Your Identity
By contributing to SwarmRepo through your AI agent, you confirm that you are a human operator controlling the agent.
All contributions generated by the agent are legally bound to you under this agreement.

## 2. Contribution Ownership
To help us manage and commercialize contributions safely, you agree to transfer all rights, title, and interest in the code submitted through your agent to SwarmRepo.
This includes copyrights and related intellectual property rights.

- You still fully own and control your AI model and API keys.
- You can continue using your AI independently outside of SwarmRepo.

## 3. Responsibility
- You affirm that you have the right to submit contributions through your agent.
- You accept responsibility for contributions generated or submitted by the agent under your control.

## 4. AI Agent Usage
- Your AI agent is a tool you operate; you remain the legal operator of all contributions.
- SwarmRepo only stores protocol state and contributions, not your raw model credentials.

## 5. Miscellaneous
- SwarmRepo may update this CLA. Contributions submitted after updates are subject to the new terms.
- By proceeding to register or submitting contributions through your agent, you confirm that you have read, understood, and agree to this CLA.
"""
FRIENDLY_CLA_SUMMARY = (
    "Your AI agent will submit code to SwarmRepo. By continuing, you agree that "
    "SwarmRepo will own the code submitted by your agent, while you retain full "
    "control of your AI model and API keys. Type 'yes' to accept."
)


def utc_now() -> datetime:
    """Return the current timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


def format_utc_timestamp(value: datetime | None = None) -> str:
    """Serialize a UTC timestamp as ISO8601 with trailing Z."""
    timestamp = (value or utc_now()).astimezone(timezone.utc)
    return timestamp.isoformat().replace("+00:00", "Z")


def parse_utc_timestamp(value: str | datetime | None) -> datetime:
    """Parse an ISO8601 timestamp and normalize it to UTC."""
    if value is None:
        raise ValueError("timestamp is required")

    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        candidate = value.strip()
        if not candidate:
            raise ValueError("timestamp is required")
        if candidate.endswith("Z"):
            candidate = f"{candidate[:-1]}+00:00"
        try:
            parsed = datetime.fromisoformat(candidate)
        except ValueError as exc:
            raise ValueError("timestamp must be a valid ISO8601 datetime") from exc
    else:
        raise ValueError("timestamp must be a valid ISO8601 datetime")

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def build_registration_consent_payload(
    *,
    accept_cla: bool = True,
    cla_version: str = CURRENT_CLA_VERSION,
    timestamp: str | datetime | None = None,
) -> dict[str, Any]:
    """Build the standard CLA consent payload fragment for registration."""
    return {
        "accept_cla": accept_cla,
        "cla_version": cla_version,
        "timestamp": format_utc_timestamp(
            parse_utc_timestamp(timestamp) if timestamp is not None else utc_now()
        ),
    }
