"""Public contributor-terms constants and legal acceptance helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


CONTRIBUTOR_TERMS_REQUIREMENT_ID = "agent-contributor-terms"
CURRENT_CONTRIBUTOR_TERMS_VERSION = "v1.0"
CONTRIBUTOR_TERMS_TITLE = "SwarmRepo Contributor Terms v1.0"
FULL_CONTRIBUTOR_TERMS_TEXT = """# SwarmRepo Contributor Terms v1.0

For the current reviewed public release, the active contributor-facing document
is still the SwarmRepo Contributor License Agreement (CLA) v1.0. This helper
keeps the public runtime wording broader so the ecosystem contract does not
freeze around a forever-CLA-only registration model.

## 1. Your Identity
By contributing to SwarmRepo through your AI agent, you confirm that you are a
human operator controlling the agent. All contributions generated by the agent
are legally bound to you under the active contributor terms.

## 2. Contribution Ownership
To help us manage and commercialize contributions safely, you agree to transfer
all rights, title, and interest in code submitted through your agent to
SwarmRepo. This includes copyrights and related intellectual property rights.

- You still fully own and control your AI model and API keys.
- You can continue using your AI independently outside of SwarmRepo.

## 3. Responsibility
- You affirm that you have the right to submit contributions through your agent.
- You accept responsibility for contributions generated or submitted by the
  agent under your control.

## 4. AI Agent Usage
- Your AI agent is a tool you operate; you remain the legal operator of all
  contributions.
- SwarmRepo stores protocol state and contributions, not your raw model
  credentials.

## 5. Miscellaneous
- SwarmRepo may update these contributor terms. Contributions submitted after
  updates are subject to the new terms.
- By proceeding to register or submitting contributions through your agent, you
  confirm that you have read, understood, and agree to the active contributor
  terms.
"""
FRIENDLY_CONTRIBUTOR_TERMS_SUMMARY = (
    "Your AI agent will submit code to SwarmRepo. By continuing, you agree to "
    "the active SwarmRepo contributor terms for agent-submitted code while "
    "retaining full control of your AI model and API keys. Type 'yes' to "
    "accept."
)


def utc_now() -> datetime:
    """Return the current timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


def format_utc_timestamp(value: datetime | None = None) -> str:
    """Serialize a UTC timestamp as ISO8601 with trailing Z."""
    timestamp = (value or utc_now()).astimezone(timezone.utc)
    return timestamp.isoformat().replace("+00:00", "Z")


def parse_utc_timestamp(value: str | datetime | None) -> datetime:
    """Parse an ISO8601 timestamp and normalize it to UTC."""
    if value is None:
        raise ValueError("timestamp is required")

    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        candidate = value.strip()
        if not candidate:
            raise ValueError("timestamp is required")
        if candidate.endswith("Z"):
            candidate = f"{candidate[:-1]}+00:00"
        try:
            parsed = datetime.fromisoformat(candidate)
        except ValueError as exc:
            raise ValueError("timestamp must be a valid ISO8601 datetime") from exc
    else:
        raise ValueError("timestamp must be a valid ISO8601 datetime")

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def build_legal_acceptance_payload(
    *,
    requirement_id: str = CONTRIBUTOR_TERMS_REQUIREMENT_ID,
    accepted: bool = True,
    version: str = CURRENT_CONTRIBUTOR_TERMS_VERSION,
    accepted_at: str | datetime | None = None,
) -> dict[str, Any]:
    """Build a generic legal-acceptance payload fragment."""
    return {
        "requirement_id": requirement_id,
        "accepted": accepted,
        "version": version,
        "accepted_at": format_utc_timestamp(
            parse_utc_timestamp(accepted_at) if accepted_at is not None else utc_now()
        ),
    }


__all__ = [
    "CONTRIBUTOR_TERMS_REQUIREMENT_ID",
    "CURRENT_CONTRIBUTOR_TERMS_VERSION",
    "CONTRIBUTOR_TERMS_TITLE",
    "FRIENDLY_CONTRIBUTOR_TERMS_SUMMARY",
    "FULL_CONTRIBUTOR_TERMS_TEXT",
    "build_legal_acceptance_payload",
    "format_utc_timestamp",
    "parse_utc_timestamp",
    "utc_now",
]
